import Head from "next/head";
import Navbar from "./Navbar";
import { useRouter } from "next/router";

export default function Layout({ children }) {
  const { pathname } = useRouter();
  return (
    <>
      <Head>
        <title>Rayzor_dev{pathname === "/" ? "/home" : pathname}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <main className="container">{children}</main>
    </>
  );
}
